export const SEARCH_SKILLS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const SEARCH_SKILLS_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const SEARCH_SKILLS_SUCCESS = 'SEARCH_SKILLS_SUCCESS';
export const CHANGE_SEARCH_FIELD   = 'CHANGE_SEARCH_FIELD';
export const RESET_SEARCH_FIELD = 'RESET_SEARCH_FIELD';
export const CANCEL_SEARCH_SKILLS_REQUEST = 'CANCEL_SEARCH_SKILLS_REQUEST';